import './globals.css'

export const metadata = {
  title: {
    default: "Next js",
    template: "%s | Learning"
  },
  description: 'Generated by Next.js',
}

//metadata

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header style={{
        backgroundColor: "lightblue",
        padding: "1rem"
      }}>
        <p>Header</p>
      </header>
        {children}
        <footer style={{
        backgroundColor: "red",
        padding: "1rem"
      }}>
        <p>aa</p>
      </footer>
        </body>
    </html>
  )
}
